[options]
version = 1
type = prx
filename = resistance_remastered.prx

; Always specify games to indicate what games are supported.
[games]
; Normal usage: specify game IDs that are supported.
UCUS98668 = true